spring:
  config:
    activate:
      on-profile: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none

s3:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  region: ${REGION}

cloud:
  aws:
    region:
      static: ${REGION}
    stack:
      auto: false

# application 실행 지연을 막기위해서 vm options에 아래 설정을 추가해줘야함
# -Dcom.amazonaws.sdk.disableEc2Metadata=true
