# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./BE
      
    - name: switch env file
      working-directory: ./BE/src/main/resources
      run: |
        cat /dev/null > ./application-prod.yml
        echo "${{ secrets.PROD }}" >> ./application-prod.yml
        cat /dev/null > ./auth.yml
        echo "${{ secrets.AUTH }}" >> ./auth.yml
        
    - name: Build with Gradle
      run: ./gradlew bootJar
      working-directory: ./BE

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: cmsskkk/issue-android
        tags: v1, latest
        registry: docker.io
        dockerfile: ./BE/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: deploy-be 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker pull cmsskkk/issue-android:latest
          docker run -d --rm --name tracker -p 8080:8080 cmsskkk/issue-android:latest 